<a href="https://colab.research.google.com/github/Vishal4002/newwork/blob/main/prac_nb.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [41]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
import seaborn as sns

In [42]:
df=pd.read_csv('/content/spam.csv',encoding='latin-1')

In [43]:
df

v1                                                 v2 Unnamed: 2  \
0      ham  Go until jurong point, crazy.. Available only ...        NaN   
1      ham                      Ok lar... Joking wif u oni...        NaN   
2     spam  Free entry in 2 a wkly comp to win FA Cup fina...        NaN   
3      ham  U dun say so early hor... U c already then say...        NaN   
4      ham  Nah I don't think he goes to usf, he lives aro...        NaN   
...    ...                                                ...        ...   
5567  spam  This is the 2nd time we have tried 2 contact u...        NaN   
5568   ham              Will Ì_ b going to esplanade fr home?        NaN   
5569   ham  Pity, * was in mood for that. So...any other s...        NaN   
5570   ham  The guy did some bitching but I acted like i'd...        NaN   
5571   ham                         Rofl. Its true to its name        NaN   

     Unnamed: 3 Unnamed: 4  
0           NaN        NaN  
1           NaN        NaN  
2           NaN        NaN  
3           NaN        NaN  
4           NaN        NaN  
...         ...        ...  
5567        NaN        NaN  
5568        NaN        NaN  
5569        NaN        NaN  
5570        NaN        NaN  
5571        NaN        NaN  

[5572 rows x 5 columns]

In [44]:
df.rename(columns={'v1':'Class_label','v2':'message'},inplace=True)

In [45]:
df

Class_label                                            message  \
0            ham  Go until jurong point, crazy.. Available only ...   
1            ham                      Ok lar... Joking wif u oni...   
2           spam  Free entry in 2 a wkly comp to win FA Cup fina...   
3            ham  U dun say so early hor... U c already then say...   
4            ham  Nah I don't think he goes to usf, he lives aro...   
...          ...                                                ...   
5567        spam  This is the 2nd time we have tried 2 contact u...   
5568         ham              Will Ì_ b going to esplanade fr home?   
5569         ham  Pity, * was in mood for that. So...any other s...   
5570         ham  The guy did some bitching but I acted like i'd...   
5571         ham                         Rofl. Its true to its name   

     Unnamed: 2 Unnamed: 3 Unnamed: 4  
0           NaN        NaN        NaN  
1           NaN        NaN        NaN  
2           NaN        NaN        NaN  
3           NaN        NaN        NaN  
4           NaN        NaN        NaN  
...         ...        ...        ...  
5567        NaN        NaN        NaN  
5568        NaN        NaN        NaN  
5569        NaN        NaN        NaN  
5570        NaN        NaN        NaN  
5571        NaN        NaN        NaN  

[5572 rows x 5 columns]

In [46]:
df.drop(['Unnamed: 2'],axis=1,inplace=True)

In [47]:
df.drop(['Unnamed: 3', 'Unnamed: 4'],axis=1,inplace=True)

In [48]:
df

Class_label                                            message
0            ham  Go until jurong point, crazy.. Available only ...
1            ham                      Ok lar... Joking wif u oni...
2           spam  Free entry in 2 a wkly comp to win FA Cup fina...
3            ham  U dun say so early hor... U c already then say...
4            ham  Nah I don't think he goes to usf, he lives aro...
...          ...                                                ...
5567        spam  This is the 2nd time we have tried 2 contact u...
5568         ham              Will Ì_ b going to esplanade fr home?
5569         ham  Pity, * was in mood for that. So...any other s...
5570         ham  The guy did some bitching but I acted like i'd...
5571         ham                         Rofl. Its true to its name

[5572 rows x 2 columns]

In [49]:
df.Class_label.value_counts()

Class_label
ham     4825
spam     747
Name: count, dtype: int64

In [50]:
df['Class_label']=df['Class_label'].apply(lambda x: 1  if x=="spam" else 0 )

In [51]:
df

Class_label                                            message
0               0  Go until jurong point, crazy.. Available only ...
1               0                      Ok lar... Joking wif u oni...
2               1  Free entry in 2 a wkly comp to win FA Cup fina...
3               0  U dun say so early hor... U c already then say...
4               0  Nah I don't think he goes to usf, he lives aro...
...           ...                                                ...
5567            1  This is the 2nd time we have tried 2 contact u...
5568            0              Will Ì_ b going to esplanade fr home?
5569            0  Pity, * was in mood for that. So...any other s...
5570            0  The guy did some bitching but I acted like i'd...
5571            0                         Rofl. Its true to its name

[5572 rows x 2 columns]

In [52]:
from sklearn.model_selection import train_test_split

In [53]:
X_train,X_test,y_train,y_test=train_test_split(df['message'],df['Class_label'],test_size=0.3,random_state=0)

In [54]:
from sklearn.feature_extraction.text import CountVectorizer

In [55]:
vectorizer=CountVectorizer(lowercase=True,stop_words='english')

In [56]:
X_train_transformed=vectorizer.fit_transform(X_train)
X_test_transformed=vectorizer.transform(X_test)

In [57]:
X_train_transformed.toarray()

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]])

In [58]:
vectorizer.get_feature_names_out()

array(['00', '000', '000pes', ..., 'ûïharry', 'ûò', 'ûówell'],
      dtype=object)

In [59]:
from sklearn.naive_bayes import MultinomialNB
classifier=MultinomialNB()
classifier.fit(X_train_transformed,y_train)

MultinomialNB()

In [60]:
y_test_predicted=classifier.predict(X_test_transformed)

In [61]:
y_test_predicted

array([0, 0, 0, ..., 0, 0, 0])

In [62]:
y_test.count()

1672

In [63]:
from sklearn.metrics import accuracy_score,confusion_matrix,classification_report

In [64]:
print('Accuracy Score:',accuracy_score(y_test,y_test_predicted))

Accuracy Score: 0.9850478468899522


In [65]:
results=confusion_matrix(y_test,y_test_predicted)
results

array([[1423,   11],
       [  14,  224]])

In [66]:
print(classification_report(y_test,y_test_predicted))

              precision    recall  f1-score   support

           0       0.99      0.99      0.99      1434
           1       0.95      0.94      0.95       238

    accuracy                           0.99      1672
   macro avg       0.97      0.97      0.97      1672
weighted avg       0.98      0.99      0.99      1672



In [76]:
new_email="Good morning sir"


In [77]:
new_email_transformed=vectorizer.transform([new_email])

In [78]:
new_email_transformed

<1x6839 sparse matrix of type '<class 'numpy.int64'>'
	with 3 stored elements in Compressed Sparse Row format>

In [79]:
classifier.predict(new_email_transformed)

array([0])